parameters:

services:
    market.dashbord.subscriber:
        class: Module\Market\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }

    order.form:
        class: Module\Market\Form\OrderForm

    market.order.subscriber:
        class: Module\Market\Subscriber\OrderSubscriber
        arguments:
            - "@order.form"
            - "@logger"
            - "@tpl"
            - "@config"
        tags:
            - { name: event.subscriber }
