parameters:

services:
    market.dashbord.subscriber:
        class: Module\Market\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }

    market.order.form:
        class: Module\Market\Form\OrderForm
        lazy: true

    market.order.subscriber:
        class: Module\Market\Subscriber\OrderSubscriber
        arguments:
            - "@market.order.form"
            - "@logger"
            - "@tpl"
            - "@event.dispatcher"
            - "%admin%"
            - "%sitename%"
        tags:
            - { name: event.subscriber }
