parameters:

services:
    news.dashbord.subscriber:
        class: Module\News\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }

    news.sitemap.subscriber:
        class: Module\News\Subscriber\SiteMapSubscriber
        arguments: [ @data.manager ]
        tags:
            - { name: event.subscriber }

    news.rss.listener:
        class: Module\News\Listener\RssListener
        tags:
            - { name: event.listener, event: kernel.response , method: onKernelResponse }
