parameters:

services:
    news.dashbord.subscriber:
        class: Module\News\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }

    news.sitemap.subscriber:
        class: Module\News\Subscriber\SiteMapSubscriber
        arguments: [ @data.manager ]
        tags:
            - { name: event.subscriber }
