parameters:

services:
    page.dashbord.subscriber:
        class: Module\Page\Subscriber\DashboardSubscriber
        arguments: [ @tpl, @data.manager ]
        tags:
            - { name: event.subscriber }

    page.sitemap.subscriber:
        class: Module\Page\Subscriber\SiteMapSubscriber
        arguments: [ @data.manager ]
        tags:
            - { name: event.subscriber }

    page.form.edit:
        class: Module\Page\Form\PageForm
        arguments: [ @module.manager, @data.manager, %sfcms.root%, %template% ]
