parameters:

services:
    page.dashbord.subscriber:
        class: Module\Page\Subscriber\DashboardSubscriber
        arguments: [ @tpl, @data.manager ]
        tags:
            - { name: event.subscriber }

    page.sitemap.subscriber:
        class: Module\Page\Subscriber\SiteMapSubscriber
        arguments: [ @data.manager ]
        tags:
            - { name: event.subscriber }
