parameters:

services:
    page.dashbord.subscriber:
        class: Module\Page\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }

    page.sitemap.subscriber:
        class: Module\Page\Subscriber\SiteMapSubscriber
        arguments: [ @mapper.page.page ]
        tags:
            - { name: event.subscriber }
