services:
    jqgrid.static.listener:
        class: Module\JqGrid\Listener\StaticListener
        arguments: ["@asset.service", "%root%"]
        tags:
            - { name: event.listener, event: static.install , method: installJqGrid }
