services:
    system.kernel.subscriber:
        class: Module\System\Subscriber\KernelSubscriber
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: event.subscriber }

    # other
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    auth:
        class: Sfcms\Auth

    cache:
        class: %cache_class%
        arguments: ["%cache_livecycle%"]

    resolver:
        class: Sfcms\Controller\Resolver
        arguments: ["@app"]

    i18n:
        class: Sfcms\i18n
        arguments: ["%sf_path%", "%assetic.output%/i18n", "%debug%"]
        calls:
            - [setLanguage, ["%language%"]]

    # routing
    route_yaml:
        class: Sfcms\Route\YmlRoute
        tags:
            - { name: event.listener, event: router.route , method: route }

    route_structure:
        class: Sfcms\Route\StructureRoute
        calls:
            - [setLogger, ["@logger"]]
        tags:
            - { name: event.listener, event: router.route , method: route }

    router:
        class: Sfcms\Router
        arguments: ["%debug%"]
        calls:
            - [setEventDispatcher, ["@event.dispatcher"]]
            - [setRequest, ["@?request="]]
            - [setLogger, ["@logger"]]
            - [setRewrite, ["%url%"]]
