services:
    system.kernel.subscriber:
        class: Module\System\Subscriber\KernelSubscriber
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: event.subscriber }

    # other
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    auth:
        class: Sfcms\Auth

    cache:
        class: %cache_class%
        arguments: ["%cache_livecycle%"]

    resolver:
        class: Sfcms\Controller\Resolver
        arguments: ["@app"]

    i18n:
        class: Sfcms\i18n
        arguments: ["%sf_path%", "%assetic.output%/i18n", "%debug%"]
        calls:
            - [setLanguage, ["%language%"]]

    router:
        class: Sfcms\Router
        calls:
            - [setRewrite, ["%url%"]]
