imports:
    - { resource: "app/config.yml" }

parameters:
    db_name: siteforever_test
    mailer_transport: ~

system:
    session:
        storage: mock
        handler: native

catalog:
    level: 5
    order_list:
        name: name
        bad: bad
