imports:
    - { resource: "app/parameters.yml" }

system:
    session:
        storage: native
        handler: native

translator:
    locale: %language%

logger:
    handlers:
        rotating_handler:
            type: rotating
            max: 1
            path: "%root%/runtime/logs/%env%.txt"

page: ~
news: ~
market: ~
ckeditor: ~
elfinder: ~
jqgrid: ~

assetic:
    debug: %debug%
    output: "%root%/static"
    filters:
        jsmin: {}
        cssmin: {}
        lessphp: {}
#    assets: {}

database:
    dsn: "mysql:host=%db_host%;port=%db_port%;dbname=%db_name%"
    login: "%db_login%"
    password: "%db_password%"
    debug: "%debug%"
    options:
        1002: "SET NAMES utf8"

doctrine: ~
#    cache:
#        metadata: { type: array }
#        query: { type: file, path: "%root%/runtime/cache" }
#        result: { type: apc }


template:
    theme: %template_theme%
    pager: %template_pager%

mailer:
    transport: %mailer_transport%
    username:  %mailer_username%
    password:  %mailer_password%
    spool:
        type: file
#        type: memory

captcha:
    width: 100
    height: 25
    color: 0x000000
    bgcolor: 0xFFFFFF

gallery:
    mime:
        - 'image/jpeg'
        - 'image/gif'
        - 'image/png'

catalog:
    level: 5
    order_list:
        name: name
        price1: price-a
        price1-d: price-d
    onPage: 5

guestbook:
    email: "%admin%"
