parameters:
    db_name: siteforever_test
    mailer_transport: ~
    template_theme: basic
    template_pager: pager_twbs2
    template_form: smarty/form_bs2.tpl

imports:
    - { resource: "app/config.yml" }

system:
    session:
        storage: mock
        handler: native

catalog:
    level: 5
    order_list:
        name: name
        bad: bad
