imports:
    - { resource: "app/parameters.yml" }

system:
    session:
        storage: native
        handler: native

translator:
    locale: %language%

logger:
    handlers:
        rotating_handler:
            type: rotating
            max: 5
            path: "%root%/runtime/logs/%env%.txt"

page: ~

assetic:
    debug: %debug%
    output: "%root%/static"
    bootstrap: true         # @deprecated

database:
    dsn: "mysql:host=%db_host%;port=%db_port%;dbname=%db_name%"
    login: "%db_login%"
    password: "%db_password%"
    debug: "%debug%"
    options:
        1002: "SET NAMES utf8"

template:
    theme: %template_theme%
    pager: %template_pager%

mailer:
    transport: %mailer_transport%
    username:  %mailer_username%
    password:  %mailer_password%
    spool:
        type: memory
#        type: file

# market config
market: ~

captcha:
    width: 100
    height: 25
    color: 0x000000
    bgcolor: 0xFFFFFF

gallery:
    mime:
        - 'image/jpeg'
        - 'image/gif'
        - 'image/png'

catalog:
    level: 5
    order_list:
        name: Name
        price: Price
