imports:
    - { resource: "app/services.yml" }
    - { resource: "app/parameters.yml" }

system:
    session:
        storage: handler
        handler: native

translator:
    locale: %language%

services:
