imports:
    - { resource: "app/parameters.yml" }

system:
    session:
        storage: native
        handler: native

translator:
    locale: %language%

logger:
    handlers:
        rotating_handler:
            type: rotating
            max: 1
            path: "%root%/runtime/logs/%env%.txt"

page: ~
news: ~
market: ~
ckeditor: ~
elfinder: ~
jqgrid: ~

assetic:
    debug: %debug%
    output: "%root%"
    filters:
        jsmin: {}
        cssmin: {}
        cssrewrite: ~
        yui_css:
            jar: "%sf_path%/app/bin/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%sf_path%/app/bin/yuicompressor-2.4.7.jar"
        pngout:
            # http://www.jonof.id.au/pngout
            bin: "%sf_path%/app/bin/pngout"
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"

database:
    debug: "%debug%"

doctrine:
    debug: %debug%
    connection:
        dbname: %db_name%
        host: %db_host%
        port: %db_port%
        user: %db_login%
        password: %db_password%
#    cache:
#        metadata: { type: filesystem }
#        query: { type: filesystem }
#        result: { type: filesystem }

template:
    parameters:
        theme: %template_theme%
        pager: %template_pager%
        form: %template_form%
        compile_check: %debug%
        force_compile: false

mailer:
    transport: %mailer_transport%
    username:  %mailer_username%
    password:  %mailer_password%
    spool:
        type: memory
#        type: file

captcha:
    width: 100
    height: 25
    color: 0x000000
    bgcolor: 0xFFFFFF

gallery:
    mime:
        - 'image/jpeg'
        - 'image/gif'
        - 'image/png'

catalog:
    level: 5
    order_list:
        name: name
        price1: price-a
        price1-d: price-d
    onPage: 5

guestbook:
    email: "%admin%"
