parameters:
    cache_livecycle: 60
    cache_class: Sfcms\Cache\CacheBlank
#    cache.class: Sfcms\Cache\CacheFile
#    cache.class: Sfcms\Cache\CacheApc
    cache_dir: "%root%/runtime/cache"

    mailer_transport: sendmail

    language: en

    template:
        cache:
            livetime: "%cache_livecycle%"

    static_dir: "%root%/static"

    db:
        dsn: "mysql:host=%db_host%;dbname=%db_name%"
        login: "%db_login%"
        password: "%db_password%"
        options:
            1002: "SET NAMES utf8"
        migration: "%db_migration%"
        debug: "%db_debug%"

    pdo_session:
        db_table: "session"

    session_storage: "@session.storage.pdo"


services:
    db:
        class: Sfcms\db
        arguments: ["@pdo"]
        calls:
            - [setLoggerClass, ["@db_logger"]]

    pdo:
        class: Sfcms\PDO
        arguments:
            params: "%db%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ["%session_storage%"]

    session.storage.mock:
        class: "Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage"

    session.storage.pdo:
        class: "Symfony\Component\HttpFoundation\Session\Storage\\NativeSessionStorage"
        arguments: [[], "@session.handler.pdo"]

    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo_session%"]

    smarty:
        class: Smarty
        properties:
            compile_check: true
            force_compile: "%debug%"

    tpl_directory:
        class: Sfcms\Tpl\Directory

    tpl:
        class: Sfcms\Tpl\Smarty
        arguments: ["%template%", "@smarty", "@tpl_directory"]

    assets:
        class: Sfcms\Assets

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    auth:
        class: Auth
        calls:
            - [setRequest, ["@request"]]

    cache:
        class: %cache_class%
        arguments: ["%cache_livecycle%"]

    eventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    resolver:
        class: Sfcms\Controller\Resolver
        arguments: ["@app"]

    i18n:
        class: Sfcms\i18n
        arguments: ["%sf_path%", "%static_dir%/i18n", "%debug%"]
        calls:
            - [setLanguage, ["%language%"]]

    router:
        class: Sfcms\Router
        calls:
            - [setRewrite, ["%url%"]]

    mailer:
        class: Swift_Mailer
        arguments: ["@mailer_transport"]

    assetManager:
        class: Assetic\AssetManager

    assetWriter:
        class: Assetic\AssetWriter
        arguments: ["%static_dir%"]
        calls:
            - [writeManagerAssets, ["@assetManager"]]
