parameters:
    cache_livecycle: 60
    cache_class: Sfcms\Cache\CacheBlank
#    cache.class: Sfcms\Cache\CacheFile
#    cache.class: Sfcms\Cache\CacheApc
    cache_dir: "%root%/runtime/cache"

    mailer_transport: mail

    db_host: localhost
    db_port: 3306

    language: en

    editor: ckeditor
#    editor: tinymce
#    editor: elrte

    pdo_session:
        db_table: "session"

    session_storage_class: "Symfony\Component\HttpFoundation\Session\Storage\\NativeSessionStorage"

services:
    app:
        synthetic: true

    kernel:
        alias: app

    request:
        synthetic: true

    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ["@session.storage"]

    session.storage.mock:
        class: "Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage"

    session.storage:
        class: "%session_storage_class%"
        arguments: [[], "@session.handler"]

    session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo_session%"]

    event.dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    locator:
        class: Symfony\Component\Config\FileLocator
        arguments: [["%root%", "%sf_path%"]]

    yaml_loader:
        class: Symfony\Component\Routing\Loader\YamlFileLoader
        arguments: ["@locator"]

    sf_router:
        class: Symfony\Component\Routing\Router
        arguments: ["@yaml_loader", "app/routes.yml", {"debug": %debug%} ]


