parameters:
    cache_livecycle: 60
    cache_class: Sfcms\Cache\CacheBlank
#    cache.class: Sfcms\Cache\CacheFile
#    cache.class: Sfcms\Cache\CacheApc
    cache_dir: "%root%/runtime/cache"

    mailer_transport: sendmail

    db_host: localhost
    db_port: 3306

    language: en

    template:
        theme:
            basic
        cache:
            livetime: "%cache_livecycle%"

    pager_template: pager_twbt

    pdo_session:
        db_table: "session"

    session_storage_class: "Symfony\Component\HttpFoundation\Session\Storage\\NativeSessionStorage"

services:
    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ["@session.storage"]

    session.storage.mock:
        class: "Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage"

    session.storage:
        class: "%session_storage_class%"
        arguments: [[], "@session.handler"]

    session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler
        arguments: ["@pdo", "%pdo_session%"]

    tpl_directory:
        class: Sfcms\Tpl\Directory

    eventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    mailer:
        class: Swift_Mailer
        arguments: ["@mailer_transport"]

    locator:
        class: Symfony\Component\Config\FileLocator
        arguments: [["%root%", "%sf_path%"]]

    yaml_loader:
        class: Symfony\Component\Routing\Loader\YamlFileLoader
        arguments: ["@locator"]

    sf_router:
        class: Symfony\Component\Routing\Router
        arguments: ["@yaml_loader", "app/routes.yml", {"debug": %debug%} ]

