parameters:
    cache_livecycle: 60
    cache_class: Sfcms\Cache\CacheBlank
#    cache.class: Sfcms\Cache\CacheFile
#    cache.class: Sfcms\Cache\CacheApc

    mailer_transport: sendmail

    language: en

    template:
        theme: basic
        cache:
            livetime: %cache_livecycle%

    static_dir: static

    db:
        login: ~
        password: ~
        dsn: "mysql:host=localhost;dbname=siteforever"
        migrtion: false
        debug: false
        options:
            1002: "SET NAMES utf8"

    pdo_session:
        db_table: "session"

    session_storage: "@session.storage.pdo"

services:
    pdo:
        class: Sfcms\PDO
        arguments:
            params: "%db%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION


    session:
        class: Symfony\Component\HttpFoundation\Session\Session
        arguments: ["%session_storage%"]

    session.storage.mock:
        class: "Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage"

    session.storage.pdo:
        class: "Symfony\Component\HttpFoundation\Session\Storage\\NativeSessionStorage"
        arguments: [[], "@session.handler.pdo"]

    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo_session%"]

    db:
        class: Sfcms\db
        arguments: ["@pdo"]

    smarty:
        class: Smarty

    tpl_directory:
        class: Sfcms\Tpl\Directory

    tpl:
        class: Sfcms\Tpl\Smarty
        arguments: ["%template%", "@smarty", "@tpl_directory"]

    assets:
        class: Sfcms\Assets

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    auth:
        class: Auth
        calls:
            - [setRequest, ["@request"]]

    cache:
        class: %cache_class%
        arguments: ["%cache_livecycle%"]

    eventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    resolver:
        class: Sfcms\Controller\Resolver
        arguments: ["@app"]

    i18n:
        class: Sfcms\i18n
        calls:
            - [setLanguage, ["%language%"]]

    router:
        class: Sfcms\Router
        calls:
            - [setRewrite, ["%url%"]]

    mailer:
        class: Swift_Mailer
        arguments: ["@mailer_transport"]

    assetManager:
        class: Assetic\AssetManager

    assetWriter:
        class: Assetic\AssetWriter
        arguments: ["%static_dir%"]
        calls:
            - [writeManagerAssets, ["@assetManager"]]
