services:
    catalog.product.form:
        class: Module\Catalog\Form\CatalogForm
        arguments: [ "@data.manager" ]

    catalog.comment.subscriber:
        class: Module\Catalog\Subscriber\CommentSwiftMailerSubscriber
        arguments: [ "%email_for_comments%" ]
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - { name: event.subscriber }

    catalog.dashbord.subscriber:
        class: Module\Catalog\Subscriber\DashboardSubscriber
        calls:
            - [ setContainer, [ "@service_container" ] ]
        tags:
            - { name: event.subscriber }

    catalog.sitemap.subscriber:
        class: Module\Catalog\Subscriber\SiteMapSubscriber
        arguments: [ "@data.manager" ]
        tags:
            - { name: event.subscriber }
