services:
    catalog.product.form:
        class: Module\Catalog\Form\CatalogForm

    catalog.comment.subscriber:
        class: Module\Catalog\Subscriber\CommentSwiftMailerSubscriber
        arguments: [ @mailer, @tpl, %email_for_comments% ]
        tags:
            - { name: event.subscriber }

    catalog.dashbord.subscriber:
        class: Module\Catalog\Subscriber\DashboardSubscriber
        arguments: [ @tpl ]
        tags:
            - { name: event.subscriber }
