parameters:

services:
    db_channel:
        class: Monolog\Logger

    db_logger:
        class: Module\Monolog\Logger\Logger
        arguments: ["@db_channel"]

    logger_channel:
        class: Monolog\Logger

    logger:
        class: Module\Monolog\Logger\Logger
        arguments: ["@logger_channel"]
