services:
    elfinder.static.listener:
        class: Module\Elfinder\Listener\StaticListener
        arguments: ["@asset.service", "%root%"]
        tags:
            - { name: event.listener, event: static.install , method: installElFinder }
