services:
    elfinder.static.listener:
        class: Module\Elfinder\Listener\StaticListener
        arguments: [""]
        tags:
            - { name: event.listener, event: static.install , method: installElFinder }
