services:
    db:
        class: Sfcms\db
        arguments: ["@database_connection"]

    data.manager:
        class: Sfcms\Data\DataManager
        lazy:  true

    data.scheme.manager:
        class: Sfcms\Data\SchemeManager
        calls:
            - [setContainer, ["@service_container"]]
