services:
    db:
        class: Sfcms\db
        arguments: ["@pdo"]
        calls:
            - [setLoggerClass, ["@db_logger"]]

    pdo:
        class: Sfcms\PDO
        arguments:
            params: "%database%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    data.manager:
        class: Sfcms\Data\DataManager
        calls:
            - [setContainer, ["@service_container"]]

    data.scheme.manager:
        class: Sfcms\Data\SchemeManager
        calls:
            - [setContainer, ["@service_container"]]
