services:
    db:
        class: Sfcms\db
#        calls:
#            - [setLoggerClass, ["@db_logger"]]

    data.manager:
        class: Sfcms\Data\DataManager
        calls:
            - [setContainer, ["@service_container"]]

    data.scheme.manager:
        class: Sfcms\Data\SchemeManager
        calls:
            - [setContainer, ["@service_container"]]
