parameters:
    doctrine.configuration.class: Doctrine\DBAL\Configuration
    doctrine.connection.class: Doctrine\DBAL\Connection
    doctrine.event_manager.class: Doctrine\Common\EventManager
    doctrine.annotation.reader.class: Doctrine\Common\Annotations\AnnotationReader
    doctrine.annotation.driver.class: Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver
    doctrine.cache.redis.class: Doctrine\Common\Cache\RedisCache
    doctrine.cache.array.class: Doctrine\Common\Cache\ArrayCache
    doctrine.cache.filesystem.class: Doctrine\Common\Cache\FilesystemCache
    doctrine.cache.memcached.class: Doctrine\Common\Cache\MemcachedCache

services:
    doctrine.event_manager:
        class: %doctrine.event_manager.class%

    doctrine.annotation.reader:
        class: %doctrine.annotation.reader.class%

    doctrine.driver:
        alias: doctrine.annotation.driver

    doctrine.annotation.driver:
        class: %doctrine.annotation.driver.class%
        arguments: ["@doctrine.annotation.reader"]

    doctrine.configuration:
        class: %doctrine.configuration.class%
        calls:
#            - ["setProxyNamespace", [ sfcms ]]
#            - ["setMetadataDriverImpl", [ "@doctrine.driver" ]]
#            - ["setSQLLogger", [ "@doctrine.logger" ]]

    doctrine.connection:
        class: %doctrine.connection.class%
