services:
    # template
    smarty:
        class: Smarty

    tpl:
        class: Module\Smarty\Component\Driver
        arguments: ["@smarty", "%template%", "%sfcms.cache_dir%"]

    smarty.plugin.form:
        class: Module\Smarty\Plugin\FormPlugin
        arguments: ~
        tags:
            - { name: smarty.plugin, type: block, plugin: form, method: block_form }
#            - { name: smarty.plugin, type: function, plugin: form_start, method: function_form_start }
#            - { name: smarty.plugin, type: function, plugin: form_end, method: function_form_end }

    smarty.plugin.asset:
        class: Module\System\Plugin\AssetPlugin
        tags:
            - { name: smarty.plugin, type: function, plugin: style, method: functionStyle }
            - { name: smarty.plugin, type: function, plugin: js, method: functionJs }
