services:
    # template
    smarty:
        class: Smarty

    tpl:
        class: Module\Smarty\Component\Driver
        arguments: ["@smarty", "%template%", "%sfcms.cache_dir%"]

    smarty.plugin.form:
        class: Module\Smarty\Plugin\FormPlugin
        arguments: [%template.form%]
        tags:
            - { name: smarty.plugin, type: block, plugin: form, method: block_form }
#            - { name: smarty.plugin, type: function, plugin: form_start, method: function_form_start }
#            - { name: smarty.plugin, type: function, plugin: form_end, method: function_form_end }
